### PR TITLE
[DESKTOP] Refactoring single form fields

### PR DESCRIPTION
**Pull request by jvnm-dev**
Some fields were duplicated or could be redone into a single field.

## Checklist

- [x] My code follows the code style of this project.
- [ ] ~~My change requires a change to the documentation.~~
- [ ] ~~I have updated the documentation accordingly.~~
- [x] I have read the **CONTRIBUTING** document.
- [ ] ~~I have added tests to cover my changes.~~
- [x] My code is commented
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jvnm-dev** [comment]
@Sylv11 What do you think of the new `atoms` folder? see [this part](https://github.com/bitsky-team/bitsky/pull/49/files#diff-0d19b81ce62fe271fcbd78d6290149c2R6).

**Comment by jvnm-dev** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>API changes but no tests!</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>Desktop changes but no cypress tests!</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>You should add an entry into CHANGELOG.md!</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Hi there, thanks for contributing!</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f34e20dc61ad729d0153600838de05b42efd134
</p>

**Comment by jvnm-dev** [comment]
> Warnings
> ⚠️	API changes but no tests!

Strange, there is no API change

> ⚠️	Desktop changes but no cypress tests!

Testing this is useless

> ⚠️	You should add an entry into CHANGELOG.md!

Not for the moment

**Comment by Sylv11** [comment]
> @Sylv11 What do you think of the new `atoms` folder? see [this part](https://github.com/bitsky-team/bitsky/pull/49/files#diff-0d19b81ce62fe271fcbd78d6290149c2R6).

> @jvm-odoo What is the purpose of this folder?

**Comment by jvnm-dev** [comment]
> @jvm-odoo What is the purpose of this folder?

It is inspired from the Atomic Design Pattern but we are not using it. By definition 

> An atom represents a basic building blocks of matter, such as a button, input or a form label. They’re not useful on their own.

Here, the atoms are all the inputs & checkbox parts who can't do anything if they are not grouped.

**Comment by jvnm-dev** [comment]
We will migrate to Atomic Design

**Pull request closed without merging**
